"""Construction of the native embedded chain complex.

For a sequence hyperdigraph, ``F_p`` is generated by explicit directed
``p``-hyperedges and

``Omega_p = {x in F_p : boundary(x) lies in F_(p-1)}``.

This module constructs filtration-compatible bases for the ``Omega_p`` spaces.
The fast branch handles a face-closed dimension, or more generally a dimension
where every hyperedge has at most one face that is late or absent at its own
birth.  The general branch uses one filtration-aware column reduction.  It is
the explicit-hyperedge analogue of the compatible-basis construction used for
persistent path homology: transformed columns are retained exactly when all
faces in their reduced boundary have appeared.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from math import inf, isfinite
from typing import Literal

from .gf2 import (
    CoordinateSolver,
    apply_columns,
    iter_set_bits,
    nullspace_basis,
    quotient_representatives,
    rank,
    transpose_columns,
)
from .model import (
    DEFINITION_ID,
    FilteredSequenceHyperdigraph,
    Hyperedge,
    SequenceHyperdigraph,
)
from .results import (
    DimensionDiagnostics,
    HomologyDiagnostics,
    HomologyResult,
)


OmegaBackend = Literal["auto", "generic", "single_missing_face"]


@dataclass(frozen=True, slots=True)
class _PreparedBoundary:
    faces: tuple[Hyperedge, ...]
    face_births: tuple[float, ...]
    face_to_lower_index: tuple[int | None, ...]
    columns: tuple[int, ...]
    rows: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class FilteredChainComplex:
    """A free filtered chain complex with bases for native ``Omega`` spaces.

    ``omega_generators[p]`` stores bit vectors in the explicit hyperedge basis
    ``hyperedges[p]``.  ``boundary_columns[p]`` stores the boundary of each
    Omega generator in the basis ``omega_generators[p-1]``.
    """

    hyperedges: tuple[tuple[Hyperedge, ...], ...]
    hyperedge_births: tuple[tuple[float, ...], ...]
    omega_generators: tuple[tuple[int, ...], ...]
    omega_births: tuple[tuple[float, ...], ...]
    omega_generator_kinds: tuple[tuple[str, ...], ...]
    boundary_columns: tuple[tuple[int, ...], ...]
    omega_backends: tuple[str, ...]
    max_late_faces_at_birth: tuple[int, ...]
    final_constraint_row_counts: tuple[int, ...]
    final_constraint_ranks: tuple[int, ...]
    face_compatible_one_skeleton: bool
    max_homology_dimension: int

    @property
    def omega_dimensions(self) -> tuple[int, ...]:
        return tuple(len(generators) for generators in self.omega_generators)


def _validate_options(max_dimension: int, omega_backend: OmegaBackend) -> None:
    if isinstance(max_dimension, bool) or not isinstance(max_dimension, int):
        raise TypeError("max_dimension must be a non-negative integer")
    if max_dimension < 0:
        raise ValueError("max_dimension must be non-negative")
    if omega_backend not in {"auto", "generic", "single_missing_face"}:
        raise ValueError(
            "omega_backend must be 'auto', 'generic', or 'single_missing_face'"
        )


def _deletion_faces(hyperedge: Hyperedge) -> tuple[Hyperedge, ...]:
    return tuple(
        hyperedge[:removed] + hyperedge[removed + 1 :]
        for removed in range(len(hyperedge))
    )


def _prepare_boundary(
    dimension: int,
    hyperedges: tuple[tuple[Hyperedge, ...], ...],
    hyperedge_births: tuple[tuple[float, ...], ...],
) -> _PreparedBoundary:
    if dimension == 0:
        return _PreparedBoundary((), (), (), tuple(0 for _ in hyperedges[0]), ())

    lower_index = {edge: index for index, edge in enumerate(hyperedges[dimension - 1])}
    lower_birth = {
        edge: hyperedge_births[dimension - 1][index]
        for edge, index in lower_index.items()
    }
    face_index: dict[Hyperedge, int] = {}
    columns: list[int] = []
    for hyperedge in hyperedges[dimension]:
        column = 0
        for face in _deletion_faces(hyperedge):
            row = face_index.setdefault(face, len(face_index))
            column ^= 1 << row
        columns.append(column)

    faces = tuple(face_index)
    face_births = tuple(lower_birth.get(face, inf) for face in faces)
    face_to_lower_index = tuple(lower_index.get(face) for face in faces)
    rows = transpose_columns(columns, len(faces))
    return _PreparedBoundary(
        faces=faces,
        face_births=face_births,
        face_to_lower_index=face_to_lower_index,
        columns=tuple(columns),
        rows=rows,
    )


def _filtered_column_compatible_basis(
    births: tuple[float, ...], prepared: _PreparedBoundary
) -> tuple[tuple[int, ...], tuple[float, ...]]:
    """Construct a compatible ``Omega`` basis in one filtered column pass.

    Domain columns are processed in increasing hyperedge-birth order.  Boundary
    rows are prioritized by decreasing face birth (an absent face has birth
    ``inf``).  Reducing a column by earlier columns preserves the allow time of
    its tracked domain vector.  If ``r`` is its reduced boundary, then

    ``entry = max(domain_birth, latest_face_birth(r))``.

    The transformed domain vectors with finite entry form a basis of the final
    embedded space, and those with entry at most ``t`` form a basis of
    ``Omega(t)``.  Unique latest-face pivots are the key: a forbidden pivot in
    any linear combination cannot be cancelled by a vector with a later pivot.
    """

    if not births:
        return (), ()

    # Remap rows so the highest set bit is the latest face.  This keeps the
    # inner reduction loop in fast integer-XOR form.
    rows_by_priority = tuple(
        sorted(
            range(len(prepared.faces)),
            key=lambda row: (prepared.face_births[row], row),
        )
    )
    priority_by_row = {
        ambient_row: priority
        for priority, ambient_row in enumerate(rows_by_priority)
    }
    ordered_columns: list[int] = []
    for column in prepared.columns:
        ordered = 0
        for ambient_row in iter_set_bits(column):
            ordered ^= 1 << priority_by_row[ambient_row]
        ordered_columns.append(ordered)

    reduced_by_pivot: dict[int, tuple[int, int]] = {}
    generated: list[tuple[int, float, int]] = []
    column_order = sorted(range(len(births)), key=lambda index: (births[index], index))
    for serial, column_index in enumerate(column_order):
        reduced = ordered_columns[column_index]
        generator = 1 << column_index
        while reduced:
            pivot = reduced.bit_length() - 1
            previous_reduction = reduced_by_pivot.get(pivot)
            if previous_reduction is None:
                reduced_by_pivot[pivot] = (reduced, generator)
                break
            reduced ^= previous_reduction[0]
            generator ^= previous_reduction[1]

        if reduced:
            pivot = reduced.bit_length() - 1
            boundary_birth = prepared.face_births[rows_by_priority[pivot]]
            entry = max(births[column_index], boundary_birth)
        else:
            entry = births[column_index]
        if isfinite(entry):
            generated.append((generator, entry, serial))

    generated.sort(key=lambda item: (item[1], item[2]))
    generators = tuple(item[0] for item in generated)
    generator_births = tuple(item[1] for item in generated)
    finite_constraint_rows = tuple(
        row
        for row, face_birth in zip(prepared.rows, prepared.face_births)
        if not isfinite(face_birth)
    )
    expected_dimension = len(births) - rank(finite_constraint_rows)
    if len(generators) != expected_dimension or rank(generators) != expected_dimension:
        raise RuntimeError("filtered column reduction produced an invalid Omega basis")

    order = sorted(
        range(len(generators)),
        key=lambda index: (generator_births[index], index),
    )
    return (
        tuple(generators[index] for index in order),
        tuple(generator_births[index] for index in order),
    )


def _single_missing_face_basis(
    births: tuple[float, ...], prepared: _PreparedBoundary
) -> tuple[tuple[int, ...], tuple[float, ...], bool, bool]:
    """Return a compatible basis if every column has at most one late face.

    The two booleans report whether the condition holds and whether every
    column was already face-closed at birth.
    """

    immediate: list[tuple[int, float]] = []
    groups: dict[int, list[int]] = defaultdict(list)
    face_closed = True
    for column_index, (column, birth) in enumerate(zip(prepared.columns, births)):
        late_rows = [
            row
            for row in iter_set_bits(column)
            if prepared.face_births[row] > birth
        ]
        if len(late_rows) > 1:
            return (), (), False, False
        if not late_rows:
            immediate.append((1 << column_index, birth))
        else:
            face_closed = False
            groups[late_rows[0]].append(column_index)

    generated: list[tuple[int, float, int]] = [
        (vector, birth, serial) for serial, (vector, birth) in enumerate(immediate)
    ]
    serial = len(generated)
    for row, columns in groups.items():
        columns.sort(key=lambda index: (births[index], index))
        expiry = prepared.face_births[row]
        constrained = [index for index in columns if births[index] < expiry]
        unconstrained = [index for index in columns if births[index] >= expiry]

        if constrained:
            pivot = constrained[0]
            for column in constrained[1:]:
                generated.append(
                    ((1 << pivot) ^ (1 << column), births[column], serial)
                )
                serial += 1
            if isfinite(expiry):
                generated.append((1 << pivot, expiry, serial))
                serial += 1
        for column in unconstrained:
            generated.append((1 << column, births[column], serial))
            serial += 1

    generated.sort(key=lambda item: (item[1], item[2]))
    generators = tuple(item[0] for item in generated)
    generator_births = tuple(item[1] for item in generated)
    if rank(generators) != len(generators):
        raise RuntimeError("single-missing-face Omega generators lost independence")
    return generators, generator_births, True, face_closed


def _construct_omega_basis(
    dimension: int,
    births: tuple[float, ...],
    prepared: _PreparedBoundary,
    backend: OmegaBackend,
) -> tuple[tuple[int, ...], tuple[float, ...], str]:
    if dimension == 0:
        return (
            tuple(1 << index for index in range(len(births))),
            births,
            "unit_f0",
        )

    if backend != "generic":
        generators, generator_births, applicable, face_closed = (
            _single_missing_face_basis(births, prepared)
        )
        if applicable:
            return (
                generators,
                generator_births,
                "face_closed_units" if face_closed else "single_missing_face_grouping",
            )
        if backend == "single_missing_face":
            raise ValueError(
                f"dimension {dimension} has a hyperedge with multiple late or absent faces"
            )

    generators, generator_births = _filtered_column_compatible_basis(
        births, prepared
    )
    return generators, generator_births, "general_circuit_column_reduction"


def _generator_kind(
    generator: int,
    entry: float,
    source_births: tuple[float, ...],
) -> str:
    """Classify a compatible generator by its explicit-hyperedge support."""

    support_size = generator.bit_count()
    if support_size == 1:
        source = next(iter(iter_set_bits(generator)))
        return (
            "unit_at_birth"
            if entry <= source_births[source]
            else "delayed_unit"
        )
    if support_size == 2:
        return "pair_cancellation"
    if support_size >= 3:
        return "multi_hyperedge_circuit"
    raise RuntimeError("an Omega basis cannot contain the zero generator")


def _max_late_faces_at_birth(
    births: tuple[float, ...], prepared: _PreparedBoundary
) -> int:
    return max(
        (
            sum(
                prepared.face_births[row] > birth
                for row in iter_set_bits(column)
            )
            for column, birth in zip(prepared.columns, births)
        ),
        default=0,
    )


def _express_boundaries(
    prepared_boundaries: tuple[_PreparedBoundary, ...],
    omega_generators: tuple[tuple[int, ...], ...],
    omega_births: tuple[tuple[float, ...], ...],
    hyperedge_births: tuple[tuple[float, ...], ...],
) -> tuple[tuple[int, ...], ...]:
    expressed: list[tuple[int, ...]] = [tuple(0 for _ in omega_generators[0])]
    for dimension in range(1, len(omega_generators)):
        lower_solver = CoordinateSolver()
        lower_cursor = 0
        columns: list[int] = []
        prepared = prepared_boundaries[dimension]

        for generator, birth in zip(
            omega_generators[dimension], omega_births[dimension]
        ):
            while (
                lower_cursor < len(omega_generators[dimension - 1])
                and omega_births[dimension - 1][lower_cursor] <= birth
            ):
                lower_solver.add(
                    omega_generators[dimension - 1][lower_cursor], lower_cursor
                )
                lower_cursor += 1

            ambient_face_boundary = apply_columns(generator, prepared.columns)
            lower_hyperedge_boundary = 0
            for face_row in iter_set_bits(ambient_face_boundary):
                lower_index = prepared.face_to_lower_index[face_row]
                if lower_index is None:
                    raise RuntimeError(
                        "an Omega generator retained a non-hyperedge boundary face"
                    )
                if hyperedge_births[dimension - 1][lower_index] > birth:
                    raise RuntimeError(
                        "an Omega generator retained a boundary face born later"
                    )
                lower_hyperedge_boundary ^= 1 << lower_index
            try:
                coordinates = lower_solver.solve(lower_hyperedge_boundary)
            except ValueError as exc:
                raise RuntimeError(
                    "a boundary could not be expressed in the lower Omega basis"
                ) from exc
            columns.append(coordinates)
        expressed.append(tuple(columns))
    return tuple(expressed)


def _face_compatible_one_skeleton(
    hyperedges: tuple[tuple[Hyperedge, ...], ...],
    hyperedge_births: tuple[tuple[float, ...], ...],
) -> bool:
    if len(hyperedges) < 2:
        return True
    zero_births = {
        edge: hyperedge_births[0][index]
        for index, edge in enumerate(hyperedges[0])
    }
    return all(
        zero_births.get((edge[0],), inf) <= birth
        and zero_births.get((edge[1],), inf) <= birth
        for edge, birth in zip(hyperedges[1], hyperedge_births[1])
    )


def build_filtered_chain_complex(
    hyperdigraph: FilteredSequenceHyperdigraph,
    max_dimension: int,
    *,
    omega_backend: OmegaBackend = "auto",
) -> FilteredChainComplex:
    """Construct the exact filtered native chain complex through ``max+1``."""

    if not isinstance(hyperdigraph, FilteredSequenceHyperdigraph):
        raise TypeError("hyperdigraph must be a FilteredSequenceHyperdigraph")
    _validate_options(max_dimension, omega_backend)
    through_dimension = max_dimension + 1

    hyperedges_list: list[tuple[Hyperedge, ...]] = []
    births_list: list[tuple[float, ...]] = []
    for dimension in range(through_dimension + 1):
        records = hyperdigraph.weighted_hyperedges(dimension)
        hyperedges_list.append(tuple(record.vertices for record in records))
        births_list.append(tuple(record.birth for record in records))
    hyperedges = tuple(hyperedges_list)
    hyperedge_births = tuple(births_list)

    prepared = tuple(
        _prepare_boundary(dimension, hyperedges, hyperedge_births)
        for dimension in range(through_dimension + 1)
    )

    omega_generators_list: list[tuple[int, ...]] = []
    omega_births_list: list[tuple[float, ...]] = []
    omega_generator_kinds: list[tuple[str, ...]] = []
    omega_backends: list[str] = []
    max_late_faces_at_birth: list[int] = []
    final_constraint_counts: list[int] = []
    final_constraint_ranks: list[int] = []

    for dimension in range(through_dimension + 1):
        generators, generator_births, selected_backend = _construct_omega_basis(
            dimension,
            hyperedge_births[dimension],
            prepared[dimension],
            omega_backend,
        )
        omega_generators_list.append(generators)
        omega_births_list.append(generator_births)
        omega_generator_kinds.append(
            tuple(
                _generator_kind(generator, entry, hyperedge_births[dimension])
                for generator, entry in zip(generators, generator_births)
            )
        )
        omega_backends.append(selected_backend)
        max_late_faces_at_birth.append(
            _max_late_faces_at_birth(
                hyperedge_births[dimension], prepared[dimension]
            )
        )
        final_rows = tuple(
            row
            for row, face_birth in zip(
                prepared[dimension].rows, prepared[dimension].face_births
            )
            if not isfinite(face_birth)
        )
        final_constraint_counts.append(len(final_rows))
        final_constraint_ranks.append(rank(final_rows))

    omega_generators = tuple(omega_generators_list)
    omega_births = tuple(omega_births_list)
    boundary_columns = _express_boundaries(
        prepared,
        omega_generators,
        omega_births,
        hyperedge_births,
    )

    for dimension in range(2, len(boundary_columns)):
        for column in boundary_columns[dimension]:
            if apply_columns(column, boundary_columns[dimension - 1]):
                raise RuntimeError("constructed boundary operators do not satisfy d^2 = 0")

    return FilteredChainComplex(
        hyperedges=hyperedges,
        hyperedge_births=hyperedge_births,
        omega_generators=omega_generators,
        omega_births=omega_births,
        omega_generator_kinds=tuple(omega_generator_kinds),
        boundary_columns=boundary_columns,
        omega_backends=tuple(omega_backends),
        max_late_faces_at_birth=tuple(max_late_faces_at_birth),
        final_constraint_row_counts=tuple(final_constraint_counts),
        final_constraint_ranks=tuple(final_constraint_ranks),
        face_compatible_one_skeleton=_face_compatible_one_skeleton(
            hyperedges, hyperedge_births
        ),
        max_homology_dimension=max_dimension,
    )


def build_chain_complex(
    hyperdigraph: SequenceHyperdigraph,
    max_dimension: int,
    *,
    omega_backend: OmegaBackend = "auto",
) -> FilteredChainComplex:
    if not isinstance(hyperdigraph, SequenceHyperdigraph):
        raise TypeError("hyperdigraph must be a SequenceHyperdigraph")
    return build_filtered_chain_complex(
        hyperdigraph.as_filtered(),
        max_dimension,
        omega_backend=omega_backend,
    )


def _chain_from_bits(vector: int, basis: tuple[Hyperedge, ...]) -> tuple[Hyperedge, ...]:
    return tuple(basis[index] for index in iter_set_bits(vector))


def compute_homology(
    hyperdigraph: SequenceHyperdigraph,
    max_dimension: int | None = None,
    *,
    representatives: bool = False,
    omega_backend: OmegaBackend = "auto",
) -> HomologyResult:
    """Compute native hyperdigraph homology exactly over GF(2)."""

    if not isinstance(hyperdigraph, SequenceHyperdigraph):
        raise TypeError("hyperdigraph must be a SequenceHyperdigraph")
    if max_dimension is None:
        max_dimension = max(0, hyperdigraph.max_dimension)
    if not isinstance(representatives, bool):
        raise TypeError("representatives must be a boolean")
    _validate_options(max_dimension, omega_backend)

    chain = build_chain_complex(
        hyperdigraph, max_dimension, omega_backend=omega_backend
    )
    betti_numbers: list[int] = []
    representative_dimensions: list[tuple[tuple[Hyperedge, ...], ...]] = []
    dimension_diagnostics: list[DimensionDiagnostics] = []

    for dimension in range(max_dimension + 1):
        boundary_rank = rank(chain.boundary_columns[dimension])
        next_boundary_rank = rank(chain.boundary_columns[dimension + 1])
        cycle_dimension = len(chain.omega_generators[dimension]) - boundary_rank
        betti = cycle_dimension - next_boundary_rank
        if betti < 0:
            raise RuntimeError("boundary rank exceeds cycle dimension")
        betti_numbers.append(betti)

        if representatives:
            cycle_equations = transpose_columns(
                chain.boundary_columns[dimension],
                len(chain.omega_generators[dimension - 1]) if dimension else 0,
            )
            cycles = nullspace_basis(
                cycle_equations, len(chain.omega_generators[dimension])
            )
            quotient = quotient_representatives(
                cycles, chain.boundary_columns[dimension + 1]
            )
            if len(quotient) != betti:
                raise RuntimeError("homology representative count is inconsistent")
            chains = tuple(
                _chain_from_bits(
                    apply_columns(vector, chain.omega_generators[dimension]),
                    chain.hyperedges[dimension],
                )
                for vector in quotient
            )
            representative_dimensions.append(chains)

        dimension_diagnostics.append(
            DimensionDiagnostics(
                dimension=dimension,
                hyperedge_count=len(chain.hyperedges[dimension]),
                omega_dimension=len(chain.omega_generators[dimension]),
                boundary_rank=boundary_rank,
                constraint_row_count=chain.final_constraint_row_counts[dimension],
                constraint_rank=chain.final_constraint_ranks[dimension],
                omega_backend=chain.omega_backends[dimension],
                generator_type_counts=tuple(
                    sorted(
                        Counter(
                            chain.omega_generator_kinds[dimension]
                        ).items()
                    )
                ),
                max_late_faces_at_birth=chain.max_late_faces_at_birth[
                    dimension
                ],
            )
        )

    ignored = sum(
        hyperdigraph.number_of_hyperedges(dimension)
        for dimension in hyperdigraph.dimensions
        if dimension > max_dimension + 1
    )
    return HomologyResult(
        betti_numbers=tuple(betti_numbers),
        representatives=tuple(representative_dimensions) if representatives else None,
        diagnostics=HomologyDiagnostics(
            definition_id=DEFINITION_ID,
            coefficient_field="GF(2)",
            dimensions=tuple(dimension_diagnostics),
            ignored_hyperedges_above=ignored,
        ),
    )


__all__ = [
    "FilteredChainComplex",
    "OmegaBackend",
    "build_chain_complex",
    "build_filtered_chain_complex",
    "compute_homology",
]
